package by.vadim_churun.ordered.speechman2.remote.xml

internal object XmlContract
{
    const val TAG_ROOT = "speech2"
    const val TAG_PERSON        = "person"
    const val TAG_PERSON_TYPE   = "personType"    // PersonType's are not yet supported.
    const val TAG_SEMINAR       = "seminar"
    const val TAG_PRODUCT       = "product"
    const val TAG_SEMDAY_SHORT  = "day"
    const val TAG_SEMDAY_LONG   = "semday"
    const val TAG_SEMCOST_SHORT = "cost"
    const val TAG_SEMCOST_LONG  = "semcost"
    const val TAG_APPOINT_SHORT = "appoint"
    const val TAG_APPOINT_LONG  = "appointment"
    const val TAG_ORDER         = "order"
    const val ATTR_PSEUDOID = "id"
    const val ATTR_PERSON_NAME    = "name"
    const val ATTR_PERSON_TYPE_ID = "typeID"
    const val ATTR_SEMINAR_NAME    = "name"
    const val ATTR_SEMINAR_CITY    = "city"
    const val ATTR_SEMINAR_ADDRESS = "address"
    const val ATTR_SEMINAR_COSTING = "costing"
    const val ATTR_SEMINAR_DELETED = "isDeleted"
    const val ATTR_SEMDAY_SEMINAR_ID = "seminarID"
    const val ATTR_SEMDAY_START      = "start"
    const val ATTR_SEMDAY_DURATION   = "duration"
    const val ATTR_SEMCOST_SEMINAR_ID   = "seminarID"
    const val ATTR_SEMCOST_PARTICIPANTS = "minParticipants"
    const val ATTR_SEMCOST_DATE         = "minDate"
    const val ATTR_SEMCOST_MONEY        = "amount"
    const val ATTR_PRODUCT_NAME         = "name"
    const val ATTR_PRODUCT_COST         = "cost"
    const val ATTR_PRODUCT_COUNT_BOXED  = "inBoxes"
    const val ATTR_PRODUCT_COUNT_CASED  = "inSuite"
    const val ATTR_PRODUCT_DELETED      = "isDeleted"
    const val ATTR_APPOINT_PERSON_ID      = "personID"
    const val ATTR_APPOINT_SEMINAR_ID     = "seminarID"
    const val ATTR_APPOINT_PURCHASE       = "paid"
    const val ATTR_APPOINT_COST           = "cost"
    const val ATTR_APPOINT_HISTORY_STATUS = "historyStatus"
    const val ATTR_APPOINT_DELETED        = "isDeleted"
    const val ATTR_ORDER_PERSON_ID      = "personID"
    const val ATTR_ORDER_PRODUCT_ID     = "productID"
    const val ATTR_ORDER_PURCHASE       = "paid"
    const val ATTR_ORDER_HISTORY_STATUS = "historyStatus"
    const val ATTR_ORDER_DELETED        = "isDeleted"
}
